//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulesEngineEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RulesEngineEditor.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actions 的本地化字符串。
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Input 的本地化字符串。
        /// </summary>
        public static string AddInput {
            get {
                return ResourceManager.GetString("AddInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Input Parameter 的本地化字符串。
        /// </summary>
        public static string AddInputParameter {
            get {
                return ResourceManager.GetString("AddInputParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Workflow 的本地化字符串。
        /// </summary>
        public static string AddWorkflow {
            get {
                return ResourceManager.GetString("AddWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arrange 的本地化字符串。
        /// </summary>
        public static string Arrange {
            get {
                return ResourceManager.GetString("Arrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 brief survey 的本地化字符串。
        /// </summary>
        public static string BriefSurvey {
            get {
                return ResourceManager.GetString("BriefSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Workflow 的本地化字符串。
        /// </summary>
        public static string CurrentWorkflow {
            get {
                return ResourceManager.GetString("CurrentWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Workflow 的本地化字符串。
        /// </summary>
        public static string CurrentWorkflowTitle {
            get {
                return ResourceManager.GetString("CurrentWorkflowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Workflow 的本地化字符串。
        /// </summary>
        public static string DeleteWorkflow {
            get {
                return ResourceManager.GetString("DeleteWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Demo 的本地化字符串。
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Demo Entity Framework 的本地化字符串。
        /// </summary>
        public static string DemoEF {
            get {
                return ResourceManager.GetString("DemoEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Demo (sample data) 的本地化字符串。
        /// </summary>
        public static string DemoSampleData {
            get {
                return ResourceManager.GetString("DemoSampleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pass pre-constructed instance of Rules Engine 的本地化字符串。
        /// </summary>
        public static string DesignPassPreconstructedInstance {
            get {
                return ResourceManager.GetString("DesignPassPreconstructedInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Starter&quot; Input Rule Parameter JSON 的本地化字符串。
        /// </summary>
        public static string DesignStarterInputRuleParamJSON {
            get {
                return ResourceManager.GetString("DesignStarterInputRuleParamJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Supports 2-way binding of Workflows 的本地化字符串。
        /// </summary>
        public static string DesignSupportsTwoWayBinding {
            get {
                return ResourceManager.GetString("DesignSupportsTwoWayBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Design Time Support: 的本地化字符串。
        /// </summary>
        public static string DesignTimeSupport {
            get {
                return ResourceManager.GetString("DesignTimeSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Inputs 的本地化字符串。
        /// </summary>
        public static string DownloadInputs {
            get {
                return ResourceManager.GetString("DownloadInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Workflows 的本地化字符串。
        /// </summary>
        public static string DownloadWorkflows {
            get {
                return ResourceManager.GetString("DownloadWorkflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag, Drop objects to change order 的本地化字符串。
        /// </summary>
        public static string DragDropObjectsOrder {
            get {
                return ResourceManager.GetString("DragDropObjectsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit in form view, JSON or switch between the two 的本地化字符串。
        /// </summary>
        public static string EditFormJsonSwitch {
            get {
                return ResourceManager.GetString("EditFormJsonSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editor for Microsoft Rules Engine - Blazor UI library intended for integration in Web or Desktop 的本地化字符串。
        /// </summary>
        public static string EditorDescription {
            get {
                return ResourceManager.GetString("EditorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enabled 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Message 的本地化字符串。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression 的本地化字符串。
        /// </summary>
        public static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Features 的本地化字符串。
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fullscreen 的本地化字符串。
        /// </summary>
        public static string Fullscreen {
            get {
                return ResourceManager.GetString("Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Params 的本地化字符串。
        /// </summary>
        public static string GlobalParams {
            get {
                return ResourceManager.GetString("GlobalParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import, Download Input Rule Parameters 的本地化字符串。
        /// </summary>
        public static string ImportDownloadInputRuleParameters {
            get {
                return ResourceManager.GetString("ImportDownloadInputRuleParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import, Download compliant Workflow json 的本地化字符串。
        /// </summary>
        public static string ImportDownloadWorkflowJson {
            get {
                return ResourceManager.GetString("ImportDownloadWorkflowJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Inputs 的本地化字符串。
        /// </summary>
        public static string ImportInputs {
            get {
                return ResourceManager.GetString("ImportInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Workflows 的本地化字符串。
        /// </summary>
        public static string ImportWorkflows {
            get {
                return ResourceManager.GetString("ImportWorkflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Name 的本地化字符串。
        /// </summary>
        public static string InputName {
            get {
                return ResourceManager.GetString("InputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Param Name 的本地化字符串。
        /// </summary>
        public static string InputParamName {
            get {
                return ResourceManager.GetString("InputParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Input Rule Parameters 的本地化字符串。
        /// </summary>
        public static string InputRuleParameters {
            get {
                return ResourceManager.GetString("InputRuleParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local Params 的本地化字符串。
        /// </summary>
        public static string LocalParams {
            get {
                return ResourceManager.GetString("LocalParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nested Rule support 的本地化字符串。
        /// </summary>
        public static string NestedRuleSupport {
            get {
                return ResourceManager.GetString("NestedRuleSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Input 的本地化字符串。
        /// </summary>
        public static string NewInputs {
            get {
                return ResourceManager.GetString("NewInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Local Param 的本地化字符串。
        /// </summary>
        public static string NewLocalParam {
            get {
                return ResourceManager.GetString("NewLocalParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Rule 的本地化字符串。
        /// </summary>
        public static string NewRule {
            get {
                return ResourceManager.GetString("NewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Workflows 的本地化字符串。
        /// </summary>
        public static string NewWorkflows {
            get {
                return ResourceManager.GetString("NewWorkflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operator 的本地化字符串。
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        public static string Operator_And {
            get {
                return ResourceManager.GetString("Operator_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AndAlso 的本地化字符串。
        /// </summary>
        public static string Operator_AndAlso {
            get {
                return ResourceManager.GetString("Operator_AndAlso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or 的本地化字符串。
        /// </summary>
        public static string Operator_Or {
            get {
                return ResourceManager.GetString("Operator_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OrElse 的本地化字符串。
        /// </summary>
        public static string Operator_OrElse {
            get {
                return ResourceManager.GetString("Operator_OrElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameters 的本地化字符串。
        /// </summary>
        public static string Parameters {
            get {
                return ResourceManager.GetString("Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please take our 的本地化字符串。
        /// </summary>
        public static string PleaseTakeOur {
            get {
                return ResourceManager.GetString("PleaseTakeOur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Real-time evaluation 的本地化字符串。
        /// </summary>
        public static string RealTimeEvaluation {
            get {
                return ResourceManager.GetString("RealTimeEvaluation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule Name 的本地化字符串。
        /// </summary>
        public static string RuleName {
            get {
                return ResourceManager.GetString("RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rules 的本地化字符串。
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rules Engine Editor 的本地化字符串。
        /// </summary>
        public static string RulesEngineEditorTitle {
            get {
                return ResourceManager.GetString("RulesEngineEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Workflow 的本地化字符串。
        /// </summary>
        public static string SaveWorkflow {
            get {
                return ResourceManager.GetString("SaveWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression 的本地化字符串。
        /// </summary>
        public static string ScopedParamExpression {
            get {
                return ResourceManager.GetString("ScopedParamExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scoped Param Name 的本地化字符串。
        /// </summary>
        public static string ScopedParamName {
            get {
                return ResourceManager.GetString("ScopedParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Standalone 的本地化字符串。
        /// </summary>
        public static string Standalone {
            get {
                return ResourceManager.GetString("Standalone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success Event 的本地化字符串。
        /// </summary>
        public static string SuccessEvent {
            get {
                return ResourceManager.GetString("SuccessEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule was successful. 的本地化字符串。
        /// </summary>
        public static string RuleWasSuccessful {
            get {
                return ResourceManager.GetString("RuleWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more adjust rules failed. 的本地化字符串。
        /// </summary>
        public static string OneOrMoreAdjustRulesFailed {
            get {
                return ResourceManager.GetString("OneOrMoreAdjustRulesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validation failed: 的本地化字符串。
        /// </summary>
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Severity: Error 的本地化字符串。
        /// </summary>
        public static string SeverityError {
            get {
                return ResourceManager.GetString("SeverityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Atleast one of Rules or WorkflowsToInject must be not empty 的本地化字符串。
        /// </summary>
        public static string RulesOrWorkflowsToInjectRequired {
            get {
                return ResourceManager.GetString("RulesOrWorkflowsToInjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow name can not be null or empty 的本地化字符串。
        /// </summary>
        public static string WorkflowNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("WorkflowNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rule Name can not be null 的本地化字符串。
        /// </summary>
        public static string RuleNameCannotBeNull {
            get {
                return ResourceManager.GetString("RuleNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value cannot be null. 的本地化字符串。
        /// </summary>
        public static string ValueCannotBeNull {
            get {
                return ResourceManager.GetString("ValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Parameter 'key') 的本地化字符串。
        /// </summary>
        public static string ParameterKey {
            get {
                return ResourceManager.GetString("ParameterKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Parameter 'value') 的本地化字符串。
        /// </summary>
        public static string ParameterValue {
            get {
                return ResourceManager.GetString("ParameterValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The input does not contain any JSON tokens 的本地化字符串。
        /// </summary>
        public static string JsonNoTokens {
            get {
                return ResourceManager.GetString("JsonNoTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected the input to start with a valid JSON token 的本地化字符串。
        /// </summary>
        public static string JsonExpectedValidToken {
            get {
                return ResourceManager.GetString("JsonExpectedValidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON value could not be converted 的本地化字符串。
        /// </summary>
        public static string JsonValueCouldNotBeConverted {
            get {
                return ResourceManager.GetString("JsonValueCouldNotBeConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expression cannot be null or empty when RuleExpressionType is LambdaExpression 的本地化字符串。
        /// </summary>
        public static string ExpressionCannotBeNullWhenLambda {
            get {
                return ResourceManager.GetString("ExpressionCannotBeNullWhenLambda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How is RulesEngineEditor working for you? 的本地化字符串。
        /// </summary>
        public static string SurveyTitle {
            get {
                return ResourceManager.GetString("SurveyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 and tell us what you think. 的本地化字符串。
        /// </summary>
        public static string TellUsWhatYouThink {
            get {
                return ResourceManager.GetString("TellUsWhatYouThink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow Name 的本地化字符串。
        /// </summary>
        public static string WorkflowName {
            get {
                return ResourceManager.GetString("WorkflowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflows 的本地化字符串。
        /// </summary>
        public static string Workflows {
            get {
                return ResourceManager.GetString("Workflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Works in conjunction with Microsoft Rules Engine 的本地化字符串。
        /// </summary>
        public static string WorksWithRulesEngine {
            get {
                return ResourceManager.GetString("WorksWithRulesEngine", resourceCulture);
            }
        }
    }
}
